# Generated by Django 2.0.8 on 2019-09-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
