# Generated by Django 2.0.8 on 2019-09-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_category_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.TextField(default='user', max_length=30),
        ),
    ]
