# Generated by Django 2.0.8 on 2019-09-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
