# Generated by Django 2.0.8 on 2019-09-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_auto_20190914_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.FileField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.FileField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(default='default_user.png', upload_to=''),
        ),
    ]
