# Generated by Django 2.0.8 on 2019-09-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_auto_20190925_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(default='defalut_user.png', upload_to=''),
        ),
    ]
