# Generated by Django 2.0.8 on 2019-09-24 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0010_auto_20190925_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='creation_date',
        ),
    ]
