# Generated by Django 2.0.8 on 2019-09-24 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0011_auto_20190925_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 24, 23, 21, 33, 199298)),
        ),
        migrations.AddField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 24, 23, 21, 33, 200297)),
        ),
    ]
