# Generated by Django 2.0.8 on 2019-09-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0012_auto_20190925_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
